import {
  blue,
  bold,
  gray,
  green,
  italic,
} from "https://deno.land/std/fmt/colors.ts";

const helpText = [
  bold(blue("# Generative AI Project")),
  "",
  italic(
    gray(
      "This project is a static website that serves as a gallery for images generated by various AI image generation services.",
    ),
  ),
  "",
  bold(blue("## Deno Tasks")),
  "",
  italic(
    gray(
      "This project uses Deno for scripting. The following tasks are available:",
    ),
  ),
  "",
  bold(green("### `deno task help`")),
  "",
  italic(gray("Displays this help message.")),
  "",
  bold(green("### `deno task index`")),
  "",
  italic(
    gray(
      "Generates the main `index.html` file for the website. It scans the 'prompts' and 'services' directories and creates a sorted list of links to the pages in those directories.",
    ),
  ),
  "",
  bold(green("### `deno task prompts`")),
  "",
  italic(
    gray(
      "Generates individual HTML pages for each prompt defined in `config.ts`. It iterates over the 'prompts' array in `config.ts` and for each prompt, it generates an HTML file containing the prompt title, text, and associated images. It also creates an `index.html` file in the 'prompts' directory that links to all the generated prompt pages.",
    ),
  ),
  "",
  bold(green("### `deno task rss`")),
  "",
  italic(
    gray(
      "Generates an RSS feed for the website. It scans the 'prompts' and 'services' directories for HTML files, gets their last modification dates, and generates an `rss-feed.xml` file with an entry for each file.",
    ),
  ),
  "",
  bold(green("### `deno task services`")),
  "",
  italic(
    gray(
      "Generates individual HTML pages for each service defined in `config.ts`. It iterates over the 'services' array in `config.ts` and for each service, it generates an HTML file containing the service name, a link to the service, and all the images generated by that service. It also creates an `index.html` file in the 'services' directory that links to all the generated service pages.",
    ),
  ),
  "",
  bold(green("### `deno task images`")),
  "",
  italic(
    gray(
      "Generates images using the Vertex AI Imagen model. It reads the 'static/data/content.json' file and for each style that has not been generated yet, it calls the Vertex AI Imagen API to generate an image. It saves the generated image to the 'images/styles' directory. This task requires a `.env` file with `GCP_PROJECT_ID` and `GCP_LOCATION` and appropriate authentication with `gcloud`.",
    ),
  ),
  "",
  bold(green("### `deno task update`")),
  "",
  italic(
    gray(
      "Runs all the other generation scripts in the correct order to completely rebuild the website. This is the command you will most likely use.",
    ),
  ),
  "",
];

console.log(helpText.join("\n"));
